In [11]:
import numpy as np

In [ ]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#     to print the data types of both the variables.

In [12]:
list_ = [1,2,3,4,5]

In [13]:
array_list = np.array(list_)

In [14]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
array_list.dtype

dtype('int64')

In [18]:
type(array_list)

numpy.ndarray

In [19]:
type(list_)

list

In [20]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [21]:
# Ans.

list_ = [1,2,3,4,5]

In [23]:
array_list = np.array([[5,6,6,6],['ash','gah','sat','hat'],[5,6,'ss','aa']])

In [24]:
array_list

array([['5', '6', '6', '6'],
       ['ash', 'gah', 'sat', 'hat'],
       ['5', '6', 'ss', 'aa']], dtype='<U21')

In [31]:
type(list_)[0:5]

list[slice(0, 5, None)]

In [42]:
array_list.dtype

dtype('int64')

In [28]:
type(array_list)

numpy.ndarray

In [33]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.


In [34]:
#Ans.
list_ = [1,2,3,4,5]

array_list = np.array(list_ , dtype = int)

In [35]:
array_list

array([1, 2, 3, 4, 5])

In [38]:
list_

[1, 2, 3, 4, 5]

In [39]:
type(array_list)

numpy.ndarray

In [40]:
type(list_)

list

In [41]:
array_list.dtype

dtype('int64')

In [43]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [44]:
# Ans.

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)

In [45]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
num_array.shape

(2, 3)

In [47]:
num_array.size

6

In [48]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [49]:
# Ans.

numpy_array= np.zeros((3,3))

In [50]:
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
numpy_array.size

9

In [52]:
numpy_array.shape

(3, 3)

In [53]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [58]:
# Ans.
identity_matrix = np.eye(5)

In [59]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
identity_matrix.shape

(5, 5)